version: '3.8'

services:
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: portfolio
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache

    working_dir: /app
    ports:
      - "0.0.0.0:8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345  
      POSTGRES_DB: portfolio
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379"

volumes:
  postgres_data:


